/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAccordion: typeof import('./src/components/ui/accordion/Accordion.vue')['default']
    AppAccordionContent: typeof import('./src/components/ui/accordion/AccordionContent.vue')['default']
    AppAccordionItem: typeof import('./src/components/ui/accordion/AccordionItem.vue')['default']
    AppAccordionTrigger: typeof import('./src/components/ui/accordion/AccordionTrigger.vue')['default']
    AppAddRoomButton: typeof import('./src/components/AddRoomButton.vue')['default']
    AppAlert: typeof import('./src/components/ui/alert/Alert.vue')['default']
    AppAlertDescription: typeof import('./src/components/ui/alert/AlertDescription.vue')['default']
    AppAlertTitle: typeof import('./src/components/ui/alert/AlertTitle.vue')['default']
    AppAvatar: typeof import('./src/components/ui/avatar/Avatar.vue')['default']
    AppAvatarFallback: typeof import('./src/components/ui/avatar/AvatarFallback.vue')['default']
    AppAvatarImage: typeof import('./src/components/ui/avatar/AvatarImage.vue')['default']
    AppBadge: typeof import('./src/components/ui/badge/Badge.vue')['default']
    AppButton: typeof import('./src/components/ui/button/Button.vue')['default']
    AppDialog: typeof import('./src/components/ui/dialog/Dialog.vue')['default']
    AppDialogClose: typeof import('./src/components/ui/dialog/DialogClose.vue')['default']
    AppDialogContent: typeof import('./src/components/ui/dialog/DialogContent.vue')['default']
    AppDialogDescription: typeof import('./src/components/ui/dialog/DialogDescription.vue')['default']
    AppDialogFooter: typeof import('./src/components/ui/dialog/DialogFooter.vue')['default']
    AppDialogHeader: typeof import('./src/components/ui/dialog/DialogHeader.vue')['default']
    AppDialogOverlay: typeof import('./src/components/ui/dialog/DialogOverlay.vue')['default']
    AppDialogScrollContent: typeof import('./src/components/ui/dialog/DialogScrollContent.vue')['default']
    AppDialogTitle: typeof import('./src/components/ui/dialog/DialogTitle.vue')['default']
    AppDialogTrigger: typeof import('./src/components/ui/dialog/DialogTrigger.vue')['default']
    AppDropdownMenu: typeof import('./src/components/ui/dropdown-menu/DropdownMenu.vue')['default']
    AppDropdownMenuCheckboxItem: typeof import('./src/components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue')['default']
    AppDropdownMenuContent: typeof import('./src/components/ui/dropdown-menu/DropdownMenuContent.vue')['default']
    AppDropdownMenuGroup: typeof import('./src/components/ui/dropdown-menu/DropdownMenuGroup.vue')['default']
    AppDropdownMenuItem: typeof import('./src/components/ui/dropdown-menu/DropdownMenuItem.vue')['default']
    AppDropdownMenuLabel: typeof import('./src/components/ui/dropdown-menu/DropdownMenuLabel.vue')['default']
    AppDropdownMenuRadioGroup: typeof import('./src/components/ui/dropdown-menu/DropdownMenuRadioGroup.vue')['default']
    AppDropdownMenuRadioItem: typeof import('./src/components/ui/dropdown-menu/DropdownMenuRadioItem.vue')['default']
    AppDropdownMenuSeparator: typeof import('./src/components/ui/dropdown-menu/DropdownMenuSeparator.vue')['default']
    AppDropdownMenuShortcut: typeof import('./src/components/ui/dropdown-menu/DropdownMenuShortcut.vue')['default']
    AppDropdownMenuSub: typeof import('./src/components/ui/dropdown-menu/DropdownMenuSub.vue')['default']
    AppDropdownMenuSubContent: typeof import('./src/components/ui/dropdown-menu/DropdownMenuSubContent.vue')['default']
    AppDropdownMenuSubTrigger: typeof import('./src/components/ui/dropdown-menu/DropdownMenuSubTrigger.vue')['default']
    AppDropdownMenuTrigger: typeof import('./src/components/ui/dropdown-menu/DropdownMenuTrigger.vue')['default']
    AppField: typeof import('./src/components/ui/field/Field.vue')['default']
    AppFieldContent: typeof import('./src/components/ui/field/FieldContent.vue')['default']
    AppFieldDescription: typeof import('./src/components/ui/field/FieldDescription.vue')['default']
    AppFieldError: typeof import('./src/components/ui/field/FieldError.vue')['default']
    AppFieldGroup: typeof import('./src/components/ui/field/FieldGroup.vue')['default']
    AppFieldLabel: typeof import('./src/components/ui/field/FieldLabel.vue')['default']
    AppFieldLegend: typeof import('./src/components/ui/field/FieldLegend.vue')['default']
    AppFieldSeparator: typeof import('./src/components/ui/field/FieldSeparator.vue')['default']
    AppFieldSet: typeof import('./src/components/ui/field/FieldSet.vue')['default']
    AppFieldTitle: typeof import('./src/components/ui/field/FieldTitle.vue')['default']
    AppInput: typeof import('./src/components/ui/input/Input.vue')['default']
    AppLabel: typeof import('./src/components/ui/label/Label.vue')['default']
    AppModeToggle: typeof import('./src/components/ModeToggle.vue')['default']
    AppRoomView: typeof import('./src/components/RoomView.vue')['default']
    AppSeparator: typeof import('./src/components/ui/separator/Separator.vue')['default']
    AppSideBar: typeof import('./src/components/SideBar.vue')['default']
    AppSonner: typeof import('./src/components/ui/sonner/Sonner.vue')['default']
    AppSpinner: typeof import('./src/components/ui/spinner/Spinner.vue')['default']
    AppTopbar: typeof import('./src/components/Topbar.vue')['default']
    AppTopBar: typeof import('./src/components/TopBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
